"""add location id to job table

Revision ID: 08b7d94c4bdf
Revises: ec28c7eec752
Create Date: 2025-06-13 13:13:20.597460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b7d94c4bdf'
down_revision = 'ec28c7eec752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.BIGINT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
