"""add is_on_monthly to key_status table

Revision ID: 11d9a06d1a9d
Revises: 96d61b04774e
Create Date: 2026-01-09 09:15:12.882962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d9a06d1a9d'
down_revision = '96d61b04774e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_on_monthly', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.drop_column('is_on_monthly')


    # ### end Alembic commands ###
