"""is it wokring

Revision ID: 22078ceed7df
Revises: 4f9f1dea2fc0
Create Date: 2026-01-23 15:56:56.256158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22078ceed7df'
down_revision = '4f9f1dea2fc0'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("vehicle", sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index("ix_vehicle_is_active", "vehicle", ["is_active"])
    # remove server default after backfill so future inserts use app default
    op.alter_column("vehicle", "is_active", server_default=None)

    with op.batch_alter_table('vehicle_submission', schema=None) as batch_op:
        batch_op.drop_index('ix_vehicle_submission_is_active')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_index('ix_vehicle_submission_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        op.drop_index("ix_vehicle_is_active", table_name="vehicle")
        op.drop_column("vehicle", "is_active")

    # ### end Alembic commands ###
