"""update key to key_status relationship to one to many

Revision ID: 25b52ee0eaf6
Revises: 5338befc2aaa
Create Date: 2026-01-07 10:15:06.568947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b52ee0eaf6'
down_revision = '5338befc2aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
