"""Add job id to deficiency record

Revision ID: 2bdd1d4f340b
Revises: d30f7e9aafae
Create Date: 2025-06-26 10:33:19.158547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdd1d4f340b'
down_revision = 'd30f7e9aafae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.BIGINT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
