"""is quoted changed to is quote sent

Revision ID: 2de112df2a10
Revises: e44660f84516
Create Date: 2025-04-24 16:27:04.058269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de112df2a10'
down_revision = 'e44660f84516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quote_sent', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_quoted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quoted', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_quote_sent')

    # ### end Alembic commands ###
