"""Add quote table

Revision ID: 30b19a14396b
Revises: f1adfa1b016f
Create Date: 2025-06-13 09:24:37.597992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b19a14396b'
down_revision = 'f1adfa1b016f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.BIGINT(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('location_id', sa.BIGINT(), nullable=True),
    sa.Column('location_address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('quote_created_on', sa.DateTime(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('quote_request', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.BIGINT(), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('job_created', sa.Boolean(), nullable=True),
    sa.Column('job_id', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote')
    # ### end Alembic commands ###
