"""add vehicle_service_event table

Revision ID: 33e54e57db6e
Revises: 9f59f56fbbec
Create Date: 2026-02-02 14:57:50.613912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e54e57db6e'
down_revision = '9f59f56fbbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_service_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=False),
    sa.Column('service_type', sa.String(length=64), nullable=False),
    sa.Column('service_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_notes', sa.Text(), nullable=True),
    sa.Column('booked_by', sa.String(length=64), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_service_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_service_event_service_type'), ['service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_service_event_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_service_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_service_event_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_service_event_service_type'))

    op.drop_table('vehicle_service_event')
    # ### end Alembic commands ###
