"""Add canceled to schedulingAttackV2

Revision ID: 3422f3e227b9
Revises: 510cbe2752a8
Create Date: 2026-01-19 16:04:17.633334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3422f3e227b9'
down_revision = '510cbe2752a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling_attack_v2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canceled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling_attack_v2', schema=None) as batch_op:
        batch_op.drop_column('canceled')

    # ### end Alembic commands ###
