"""baseline after rebase

Revision ID: 357f33ff112a
Revises: 
Create Date: 2025-04-25 14:14:01.795528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357f33ff112a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_expiry', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('quote_expiry')

    # ### end Alembic commands ###
