"""removed unique constraint for key_Status to key_id

Revision ID: 372cff590d95
Revises: 9c768f58c0e0
Create Date: 2026-01-06 15:31:44.023732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372cff590d95'
down_revision = '9c768f58c0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.drop_index('ix_key_status_key_id')
        batch_op.create_index(batch_op.f('ix_key_status_key_id'), ['key_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_status_key_id'))
        batch_op.create_index('ix_key_status_key_id', ['key_id'], unique=True)

    # ### end Alembic commands ###
