"""updated quote with quote items

Revision ID: 3a4861dddef7
Revises: cbb5224ce715
Create Date: 2025-11-17 15:04:33.391321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4861dddef7'
down_revision = 'cbb5224ce715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('quote_deficiency_link', schema=None) as batch_op:
        batch_op.alter_column('quote_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('deficiency_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.drop_constraint('quote_deficiency_link_deficiency_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'deficiency', ['deficiency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_deficiency_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quote_deficiency_link_deficiency_id_fkey', 'deficiency', ['deficiency_id'], ['deficiency_id'])
        batch_op.alter_column('deficiency_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('quote_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
