"""convert quote deficiency ids to big integer and changed quote_deficiny_link foreign key to deficiency.deficiency_id

Revision ID: 4d06a2fef68c
Revises: 3a4861dddef7
Create Date: 2025-11-17 16:22:09.751548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d06a2fef68c'
down_revision = '3a4861dddef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('quote_deficiency_link', schema=None) as batch_op:
        batch_op.alter_column('deficiency_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.drop_constraint('quote_deficiency_link_deficiency_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'deficiency', ['deficiency_id'], ['deficiency_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_deficiency_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quote_deficiency_link_deficiency_id_fkey', 'deficiency', ['deficiency_id'], ['id'])
        batch_op.alter_column('deficiency_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
