"""remove vehicle deficiency linked to submission, add transmission, warning lights and safe to operate to submission

Revision ID: 4d7c125ade4d
Revises: e997f739c323
Create Date: 2026-02-03 09:58:24.470651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7c125ade4d'
down_revision = 'e997f739c323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_deficiency', schema=None) as batch_op:
        batch_op.drop_index('ix_vehicle_deficiency_source_submission_id')
        batch_op.drop_constraint('vehicle_deficiency_source_submission_id_fkey', type_='foreignkey')
        batch_op.drop_column('source_submission_id')

    with op.batch_alter_table('vehicle_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transmission_level', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('warning_lights', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('safe_to_operate', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_submission', schema=None) as batch_op:
        batch_op.drop_column('safe_to_operate')
        batch_op.drop_column('warning_lights')
        batch_op.drop_column('transmission_level')

    with op.batch_alter_table('vehicle_deficiency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_submission_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('vehicle_deficiency_source_submission_id_fkey', 'vehicle_submission', ['source_submission_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_vehicle_deficiency_source_submission_id', ['source_submission_id'], unique=False)

    # ### end Alembic commands ###
