"""Add is active to vehicle for soft deletion

Revision ID: 4f9f1dea2fc0
Revises: 75b171b02a1a
Create Date: 2026-01-23 15:46:32.084620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9f1dea2fc0'
down_revision = '75b171b02a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_vehicle_submission_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_submission_is_active'))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
