"""add scheduled_date to SchedulingAttackV2

Revision ID: 510cbe2752a8
Revises: b91bdcf2bfed
Create Date: 2026-01-19 14:43:32.521703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510cbe2752a8'
down_revision = 'b91bdcf2bfed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('scheduling_attack_v2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('location_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling_attack_v2', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.drop_column('scheduled_date')


    # ### end Alembic commands ###
