"""Add DeficiencyRecord table

Revision ID: 521b497a0d2f
Revises: 911401789948
Create Date: 2025-04-24 09:18:35.563135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521b497a0d2f'
down_revision = '911401789948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deficiency_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reported_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('is_monthly_access', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('proposed_solution', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('tech_name', sa.String(length=255), nullable=True),
    sa.Column('tech_image_link', sa.String(length=1024), nullable=True),
    sa.Column('job_link', sa.String(length=1024), nullable=True),
    sa.Column('service_line_name', sa.String(length=255), nullable=True),
    sa.Column('service_line_icon_link', sa.String(length=1024), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deficiency_record')
    # ### end Alembic commands ###
