"""add site status to keys table

Revision ID: 5338befc2aaa
Revises: 372cff590d95
Create Date: 2026-01-06 15:39:54.694917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5338befc2aaa'
down_revision = '372cff590d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_status', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.drop_column('site_status')


    # ### end Alembic commands ###
