"""add service occurence table

Revision ID: 5e325c37ce13
Revises: 1770a256287a
Create Date: 2025-09-19 13:09:46.414151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e325c37ce13'
down_revision = '1770a256287a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=True),
    sa.Column('job_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_month', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('spr_hours_actual', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fa_hours_actual', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('number_of_fa_days', sa.Integer(), nullable=False),
    sa.Column('number_of_spr_days', sa.Integer(), nullable=False),
    sa.Column('number_of_fa_techs', sa.Integer(), nullable=False),
    sa.Column('number_of_spr_techs', sa.Integer(), nullable=False),
    sa.Column('travel_minutes_per_appt', sa.Integer(), nullable=True),
    sa.Column('travel_minutes_total', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('location_on_hold', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('row_inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_so_job')
    )
    with op.batch_alter_table('service_occurrence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_occurrence_location_id'), ['location_id'], unique=False)
        batch_op.create_index('ix_so_location_month', ['location_id', 'observed_month'], unique=False)
        batch_op.create_index('ix_so_month', ['observed_month'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('service_occurrence', schema=None) as batch_op:
        batch_op.drop_index('ix_so_month')
        batch_op.drop_index('ix_so_location_month')
        batch_op.drop_index(batch_op.f('ix_service_occurrence_location_id'))

    op.drop_table('service_occurrence')
    # ### end Alembic commands ###
