"""add attachment uploaded by and has attachment to deficiency

Revision ID: 5f42dd5c2034
Revises: 08b7d94c4bdf
Create Date: 2025-06-16 16:14:08.277307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f42dd5c2034'
down_revision = '08b7d94c4bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_attachment', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('attachment_uploaded_by', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency', schema=None) as batch_op:
        batch_op.drop_column('attachment_uploaded_by')
        batch_op.drop_column('has_attachment')

    # ### end Alembic commands ###
