"""remove is_current from service_recurrence

Revision ID: 60ae165a8a86
Revises: 18055f06b9a9
Create Date: 2025-09-09 08:53:11.739283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ae165a8a86'
down_revision = '18055f06b9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_service_recurrence_is_current")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_service_recurrence_is_current", "service_recurrence", ["is_current"])

    # ### end Alembic commands ###
