"""add QuoteItem and InvoiceItem tables

Revision ID: 662fea1abe3f
Revises: 5f42dd5c2034
Create Date: 2025-06-17 09:51:38.304012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662fea1abe3f'
down_revision = '5f42dd5c2034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('service_trade_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.Enum('labor', 'part', name='invoice_item_type'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.BigInteger(), nullable=False),
    sa.Column('service_trade_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.Enum('labor', 'part', name='quote_item_type'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.quote_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_item')
    op.drop_table('invoice_item')
    # ### end Alembic commands ###
