"""add job and clock_event tables

Revision ID: 6b83fd609e1b
Revises: 357f33ff112a
Create Date: 2025-06-10 15:33:37.123867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b83fd609e1b'
down_revision = '357f33ff112a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('job_status', sa.String(length=255), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('completed_on', sa.DateTime(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('total_on_site_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('clock_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tech_name', sa.String(length=255), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clock_event')
    op.drop_table('job')
    # ### end Alembic commands ###
