"""updating ServiceRecurrence table to accommodate multiple services per location

Revision ID: 6eb2f303882a
Revises: 60ae165a8a86
Create Date: 2025-09-18 11:44:06.175909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb2f303882a'
down_revision = '60ae165a8a86'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('service_recurrence', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sr_one_per_location', type_='unique')
        batch_op.create_index('ix_sr_location_month', ['location_id', 'month'], unique=False)
        batch_op.create_index('ix_sr_location_service', ['location_id', 'service_id'], unique=False)
        batch_op.create_index('ix_sr_st_recurrence_id', ['st_recurrence_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_recurrence', schema=None) as batch_op:
        batch_op.drop_index('ix_sr_st_recurrence_id')
        batch_op.drop_index('ix_sr_location_service')
        batch_op.drop_index('ix_sr_location_month')
        batch_op.create_unique_constraint('uq_sr_one_per_location', ['location_id'])


    # ### end Alembic commands ###
