"""readding updated_by to vehicle deficiency

Revision ID: 72afa9ecf07a
Revises: 7ed654a04a48
Create Date: 2026-02-03 11:04:00.774219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72afa9ecf07a'
down_revision = '7ed654a04a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_deficiency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_deficiency', schema=None) as batch_op:
        batch_op.drop_column('updated_by')

    # ### end Alembic commands ###
