"""Adding quoting tracking to table

Revision ID: 7491b6c2aff6
Revises: 62d12f651177
Create Date: 2025-04-24 15:01:26.832003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7491b6c2aff6'
down_revision = '62d12f651177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quoted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_quote_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.drop_column('is_quote_approved')
        batch_op.drop_column('is_quoted')

    # ### end Alembic commands ###
