"""add vehicle and vehiclesubmission tables

Revision ID: 75b171b02a1a
Revises: 92413446aa72
Create Date: 2026-01-23 15:31:06.374702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b171b02a1a'
down_revision = '92413446aa72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('license_plate', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('make_model', sa.String(length=64), nullable=False),
    sa.Column('current_driver_name', sa.String(length=64), nullable=True),
    sa.Column('fuel_tank_size_l', sa.Float(), nullable=True),
    sa.Column('fuel_economy_l_per_100km', sa.Float(), nullable=True),
    sa.Column('latest_current_km', sa.Integer(), nullable=True),
    sa.Column('latest_service_due_km', sa.Integer(), nullable=True),
    sa.Column('latest_oil_level', sa.String(length=16), nullable=True),
    sa.Column('latest_coolant_level', sa.String(length=16), nullable=True),
    sa.Column('latest_deficiency_notes', sa.Text(), nullable=True),
    sa.Column('last_submission_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_submission_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_last_submission_at'), ['last_submission_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_license_plate'), ['license_plate'], unique=True)

    op.create_table('vehicle_submission',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_by', sa.String(length=64), nullable=False),
    sa.Column('current_km', sa.Integer(), nullable=True),
    sa.Column('service_due_km', sa.Integer(), nullable=True),
    sa.Column('oil_level', sa.String(length=16), nullable=True),
    sa.Column('coolant_level', sa.String(length=16), nullable=True),
    sa.Column('deficiency_notes', sa.Text(), nullable=True),
    sa.CheckConstraint('current_km >= 0', name='ck_vs_current_km_nonneg'),
    sa.CheckConstraint('service_due_km >= 0', name='ck_vs_service_due_km_nonneg'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_submission_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_submission_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_submission_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_submission_submitted_at'))

    op.drop_table('vehicle_submission')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_license_plate'))
        batch_op.drop_index(batch_op.f('ix_vehicle_last_submission_at'))

    op.drop_table('vehicle')
    # ### end Alembic commands ###
