"""removed unecessary columns from monthly snapshots

Revision ID: 7d38950aa58d
Revises: fdfd59e0ef1f
Create Date: 2025-12-16 12:57:27.195345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d38950aa58d'
down_revision = 'fdfd59e0ef1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
