"""Add deficiency_id and unique constraint

Revision ID: 879c218014bf
Revises: 521b497a0d2f
Create Date: 2025-04-24 09:28:50.458918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879c218014bf'
down_revision = '521b497a0d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deficiency_id', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['deficiency_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('deficiency_id')

    # ### end Alembic commands ###
