"""Add forward schedule coverage table

Revision ID: 92413446aa72
Revises: d28adb97af01
Create Date: 2026-01-22 11:12:20.113721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92413446aa72'
down_revision = 'd28adb97af01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forward_schedule_week',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('week_start_local', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_end_local', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booked_hours', sa.Float(), nullable=False),
    sa.Column('unavailable_hours', sa.Float(), nullable=False),
    sa.Column('available_hours', sa.Float(), nullable=False),
    sa.Column('released_appointments', sa.Integer(), nullable=False),
    sa.Column('utilization_pct', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_hours >= 0', name='ck_fsw_available_nonneg'),
    sa.CheckConstraint('booked_hours >= 0', name='ck_fsw_booked_nonneg'),
    sa.CheckConstraint('utilization_pct >= 0', name='ck_fsw_util_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forward_schedule_week', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forward_schedule_week_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forward_schedule_week_week_start_local'), ['week_start_local'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forward_schedule_week', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forward_schedule_week_week_start_local'))
        batch_op.drop_index(batch_op.f('ix_forward_schedule_week_generated_at'))

    op.drop_table('forward_schedule_week')
    # ### end Alembic commands ###
