"""add returned by to key status

Revision ID: 96d61b04774e
Revises: cdb481d009c6
Create Date: 2026-01-09 08:35:43.362464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d61b04774e'
down_revision = 'cdb481d009c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_by', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.drop_column('returned_by')


    # ### end Alembic commands ###
