"""added inserted_at to key status table

Revision ID: 9c768f58c0e0
Revises: fd8c09f6c77e
Create Date: 2026-01-06 15:27:09.834546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c768f58c0e0'
down_revision = 'fd8c09f6c77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.drop_column('inserted_at')


    # ### end Alembic commands ###
