"""Add backflowAutomationMetric table

Revision ID: a07a1efc063c
Revises: 5e325c37ce13
Create Date: 2025-10-21 10:01:29.091337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07a1efc063c'
down_revision = '5e325c37ce13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )

    # ### end Alembic commands ###


def downgrade():

    op.drop_table('metric')
    # ### end Alembic commands ###
