"""adding added to service trade column for job and location

Revision ID: c96e3b7bf16c
Revises: 4e7bc47c12f2
Create Date: 2025-06-25 12:25:44.424837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96e3b7bf16c'
down_revision = '4e7bc47c12f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on_st', sa.DateTime(), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on_st', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('created_on_st')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('created_on_st')

    # ### end Alembic commands ###
