"""updated quote deficiency link

Revision ID: cbb5224ce715
Revises: 3d4ccd7820c9
Create Date: 2025-11-17 14:51:37.701115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb5224ce715'
down_revision = '3d4ccd7820c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_deficiency_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.BIGINT(), nullable=True),
    sa.Column('deficiency_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['deficiency_id'], ['deficiency.deficiency_id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.quote_id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('linked_deficiency_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_deficiency_id', sa.BIGINT(), autoincrement=False, nullable=True))


    op.drop_table('quote_deficiency_link')
    # ### end Alembic commands ###
