"""adding vehicle_deficiencies

Revision ID: cca528c12f0b
Revises: 33e54e57db6e
Create Date: 2026-02-02 15:49:45.704762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca528c12f0b'
down_revision = '33e54e57db6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_deficiency',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger(), nullable=False),
    sa.Column('source_submission_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.String(length=64), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_submission_id'], ['vehicle_submission.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_deficiency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_deficiency_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_deficiency_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_deficiency_source_submission_id'), ['source_submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_deficiency_vehicle_id'), ['vehicle_id'], unique=False)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('latest_deficiency_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_deficiency_notes', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('vehicle_deficiency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_deficiency_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_deficiency_source_submission_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_deficiency_is_resolved'))
        batch_op.drop_index(batch_op.f('ix_vehicle_deficiency_category'))

    op.drop_table('vehicle_deficiency')
    # ### end Alembic commands ###
