"""added db field for air tag in key_status

Revision ID: cdb481d009c6
Revises: 25b52ee0eaf6
Create Date: 2026-01-07 13:50:15.842432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb481d009c6'
down_revision = '25b52ee0eaf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('air_tag', sa.String(length=55), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.drop_column('air_tag')


    # ### end Alembic commands ###
