"""add job_item_technician table

Revision ID: cef20e999406
Revises: 0068ad678ed8
Create Date: 2025-08-14 14:49:08.427275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef20e999406'
down_revision = '0068ad678ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_item_technician',
    sa.Column('job_item_id', sa.BIGINT(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('is_tech', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('job_item_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('related_job_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on_st', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_item_id'),
    sa.UniqueConstraint('job_item_id', name='uq_job_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_item_technician')
    # ### end Alembic commands ###
