"""added weekly scheduling volume tables

Revision ID: d28adb97af01
Revises: 3422f3e227b9
Create Date: 2026-01-21 14:40:34.333834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28adb97af01'
down_revision = '3422f3e227b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_scheduling_state',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('weekly_scheduling_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=False),
    sa.Column('scheduled_count', sa.Integer(), nullable=True),
    sa.Column('rescheduled_count', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start', 'period_end', 'job_type', name='uq_weekly_scheduling_stats_period_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_scheduling_stats')
    op.drop_table('jobs_scheduling_state')
    # ### end Alembic commands ###
