"""add is job complete to deficiency record

Revision ID: d30f7e9aafae
Revises: c96e3b7bf16c
Create Date: 2025-06-26 09:48:11.376713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30f7e9aafae'
down_revision = 'c96e3b7bf16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_job_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.drop_column('is_job_complete')

    # ### end Alembic commands ###
