"""added quote in draft

Revision ID: e44660f84516
Revises: 7491b6c2aff6
Create Date: 2025-04-24 16:02:52.935311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44660f84516'
down_revision = '7491b6c2aff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quote_in_draft', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deficiency_record', schema=None) as batch_op:
        batch_op.drop_column('is_quote_in_draft')

    # ### end Alembic commands ###
