"""add version to meeting_minutes

Revision ID: e48e4c296406
Revises: 64cf7b60126d
Create Date: 2025-07-08 11:49:00.752714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48e4c296406'
down_revision = '64cf7b60126d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_minute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_minute', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('modified_by')

    # ### end Alembic commands ###
