"""add clock in and clock out to clock event table

Revision ID: e58893549af1
Revises: 69f36fd99563
Create Date: 2025-06-18 12:30:30.896535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58893549af1'
down_revision = '69f36fd99563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clock_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock_in', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('clock_out', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('tech_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clock_event', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('tech_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('clock_out')
        batch_op.drop_column('clock_in')

    # ### end Alembic commands ###
