"""add deficiency table for 2024-2025 review

Revision ID: e82f8366d2da
Revises: 96fa0c01efae
Create Date: 2025-06-12 16:14:31.785745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82f8366d2da'
down_revision = '96fa0c01efae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deficiency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deficiency_id', sa.BIGINT(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('reported_by', sa.String(length=255), nullable=True),
    sa.Column('service_line', sa.String(length=100), nullable=True),
    sa.Column('job_id', sa.BIGINT(), nullable=False),
    sa.Column('location_id', sa.BIGINT(), nullable=False),
    sa.Column('deficiency_created_on', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('orphaned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deficiency_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deficiency')
    # ### end Alembic commands ###
