"""vehicle_deficiency transitioning to a more servicetrade style deficiency

Revision ID: e997f739c323
Revises: cca528c12f0b
Create Date: 2026-02-02 16:06:01.319483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e997f739c323'
down_revision = 'cca528c12f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_deficiency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_index('ix_vehicle_deficiency_category')
        batch_op.drop_index('ix_vehicle_deficiency_is_resolved')
        batch_op.create_index(batch_op.f('ix_vehicle_deficiency_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_deficiency_status'), ['status'], unique=False)
        batch_op.drop_column('resolution_notes')
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('category')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('reported_by')
        batch_op.drop_column('reported_at')
        batch_op.drop_column('is_resolved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_deficiency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resolved', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reported_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reported_by', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resolved_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_vehicle_deficiency_status'))
        batch_op.drop_index(batch_op.f('ix_vehicle_deficiency_severity'))
        batch_op.create_index('ix_vehicle_deficiency_is_resolved', ['is_resolved'], unique=False)
        batch_op.create_index('ix_vehicle_deficiency_category', ['category'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('status')
        batch_op.drop_column('severity')

    # ### end Alembic commands ###
