"""Added is confirmed to service occurence

Revision ID: e9bfeac9e62c
Revises: 11d9a06d1a9d
Create Date: 2026-01-15 14:46:59.105608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bfeac9e62c'
down_revision = '11d9a06d1a9d'
branch_labels = None
depends_on = None


def upgrade():
    # 1) Add column WITH default, allow null temporarily
    with op.batch_alter_table('service_occurrence', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_confirmed',
                sa.Boolean(),
                nullable=True,
                server_default=sa.false()
            )
        )

    # 2) Backfill any existing rows explicitly (defensive)
    op.execute(
        "UPDATE service_occurrence SET is_confirmed = false WHERE is_confirmed IS NULL"
    )

    # 3) Enforce NOT NULL and drop the server default
    with op.batch_alter_table('service_occurrence', schema=None) as batch_op:
        batch_op.alter_column(
            'is_confirmed',
            nullable=False,
            server_default=None
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_occurrence', schema=None) as batch_op:
        batch_op.drop_column('is_confirmed')


    # ### end Alembic commands ###
