"""add linked_deficiency_id to quotes

Revision ID: ec28c7eec752
Revises: 30b19a14396b
Create Date: 2025-06-13 09:46:30.547638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec28c7eec752'
down_revision = '30b19a14396b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_deficiency_id', sa.BIGINT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('linked_deficiency_id')

    # ### end Alembic commands ###
