"""scheduling attack v2

Revision ID: f877bdb725f4
Revises: 7a4a344434a8
Create Date: 2026-01-19 11:13:44.016280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f877bdb725f4'
down_revision = '7a4a344434a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduling_attack_v2',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('scheduled', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('reached_out', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=1020), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('scheduling_reached_out', schema=None) as batch_op:
        batch_op.drop_constraint('scheduling_reached_out_job_id_key', type_='unique')
        batch_op.drop_index('ix_scheduling_reached_out_job_id')
        batch_op.create_index(batch_op.f('ix_scheduling_reached_out_job_id'), ['job_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling_reached_out', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduling_reached_out_job_id'))
        batch_op.create_index('ix_scheduling_reached_out_job_id', ['job_id'], unique=False)
        batch_op.create_unique_constraint('scheduling_reached_out_job_id_key', ['job_id'])

    op.drop_table('scheduling_attack_v2')
    # ### end Alembic commands ###
