"""adding tables for key tracking

Revision ID: fd8c09f6c77e
Revises: 7d38950aa58d
Create Date: 2026-01-06 15:16:13.249762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8c09f6c77e'
down_revision = '7d38950aa58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('keycode', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.BigInteger(), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('home_location', sa.String(length=255), nullable=True),
    sa.Column('annual_month', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keys_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_keys_keycode'), ['keycode'], unique=True)
        batch_op.create_index('ix_keys_route', ['route'], unique=False)

    op.create_table('key_addresses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('key_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id', 'address', name='uq_key_addresses_key_id_address')
    )
    with op.batch_alter_table('key_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_addresses_key_id'), ['key_id'], unique=False)

    op.create_table('key_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('key_location', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_status_key_id'), ['key_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('key_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_status_key_id'))

    op.drop_table('key_status')
    with op.batch_alter_table('key_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_addresses_key_id'))

    op.drop_table('key_addresses')
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.drop_index('ix_keys_route')
        batch_op.drop_index(batch_op.f('ix_keys_keycode'))
        batch_op.drop_index(batch_op.f('ix_keys_barcode'))

    op.drop_table('keys')
    # ### end Alembic commands ###
