"""add table for monthly route specialists

Revision ID: fdfd59e0ef1f
Revises: 4d06a2fef68c
Create Date: 2025-12-16 12:54:33.311916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdfd59e0ef1f'
down_revision = '4d06a2fef68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_route_snapshot',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('completed_jobs_count', sa.Integer(), nullable=False),
    sa.Column('top_technicians', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_route_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_route_snapshot_last_updated_at'), ['last_updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_route_snapshot_location_id'), ['location_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('monthly_route_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_route_snapshot_location_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_route_snapshot_last_updated_at'))

    op.drop_table('monthly_route_snapshot')
    # ### end Alembic commands ###
